window.TEXTS = [
 'Tukehtukaa ruotoihini }:>',
 'Koita ite uida tämmösillä\nvatkaimilla..',
 'Pissin juomaveteesi',
 'Olen perheellinen,\nmikset säästä mua?!',
 'Maistun pahalle..',
 'Eikö täällä saa edes\nkuturauhaa?',
 'Sukupuuttoonko minua ajat?',
 'Ite olit ennen kala',
 'Onneksi en sheivannut.',
 'Hyppää vaikka kaivoon',
 'Syäräkkö sää mut tahrot?',
 'Et sää mua pois saa',
 'Olen täynnä luteita',
 'Teeppä ite perässä',
 //'Mulkero..',
 'Oikeesti et sais edes\nmatoa vesilätäköstä',
 'Kuolin sitten sukupuuttoon',
 'Pah, ikineitsyt',
 'Rihmaläjä koitui kuolemaksi',
 'Tapoit sitten viimisen\nlajinedustajan',
 'Hae kalas pakastealtaasta',
 'Etpä ole itekkään\nkumman näkönen',
 'Ei aina voi olla\npenaalin terävin kynä',
];
